### ISSUE TITLE
Node placement

### ISSUE THREAD

**Issue by eastlin7** [eastlin7/TreeVisualizer#5]
Root node gets placed at position X Y

Where X = Width of window / 2
And Y = Top of the display with a margin to make sure the circle is within the display

**Comment by isakvi** [comment]
A very naive method in NodeVisualizer class shows that the drawing of nodes (as circles) on a canvas is a reasonable way to implement this

**Comment by isakvi** [comment]
The method in NodeVisualizer is working correctly, but right now the issue is with the logic in the drawNode method of the Tree class

**Comment by isakvi** [comment]
Logic is now working. Our next challenge is to place nodes so that they don't overlap.
At the moment it seems like a very complicated task.

**Comment by isakvi** [comment]
I have pondered on a solution to nodes overlapping and I've come up with this:

Instead of some complicated algorithm we could give the circles a smaller diameter and have their x (& y ?) distance from their parent be a random value within a given interval.

That would make overlapping less common and give each branch a special touch, like a tree in nature.

Thoughts?

**Comment by eastlin7** [comment]
Sounds like an interesting approach, try it out! :smile:

**Comment by isakvi** [comment]
It has now been implemented in a new branch.

**Comment by eastlin7** [comment]
Its merged and implemented now
